export const background = '#efefefef'
export const black = '#666666'
export const white = '#eeeeee'
export const pieceBlack = '#222222'
export const pieceWhite = '#ffffff'
export const pieceBorder = '#000000'
export const yellow = '#eede00'
export const purple = '#de00ee'
