"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.black = '#111111';
exports.darkGray = '#666666';
exports.lightGray = '#eeeeee';
exports.white = '#ffffff';
exports.yellow = '#eede00';
exports.purple = '#de00ee';
exports.background = exports.white;
exports.tileBlack = exports.darkGray;
exports.tileWhite = exports.lightGray;
exports.userHighlight = exports.yellow;
exports.computerHightlight = exports.purple;
exports.pieceBorder = exports.black;
