import {
  rook,
  knight,
  bishop,
  queen,
  king,
  pawn,
  empty,
} from "../../utils/pieces"

import { Board, black, white } from "../../utils/game_helpers"

export const initialBoard: Board = [
  [
    new rook(black),
    new knight(black),
    new bishop(black),
    new queen(black),
    new king(black),
    new bishop(black),
    new knight(black),
    new rook(black),
  ],
  [
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
  ],
  [
    new rook(white),
    new knight(white),
    new bishop(white),
    new queen(white),
    new king(white),
    new bishop(white),
    new knight(white),
    new rook(white),
  ],
]

export const boardWithMoves: Board = [
  [
    new rook(black),
    new knight(black),
    new bishop(black),
    new queen(black),
    new king(black),
    new bishop(black),
    new knight(black),
    new rook(black),
  ],
  [
    new pawn(black),
    new pawn(black),
    new empty(),
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
    new pawn(black),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new empty(),
    new empty(),
    new pawn(black),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new pawn(white),
    new empty(),
    new empty(),
    new empty(),
  ],
  [
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new empty(),
    new knight(white),
    new empty(),
    new empty(),
  ],
  [
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new pawn(white),
    new empty(),
    new pawn(white),
    new pawn(white),
  ],
  [
    new rook(white),
    new knight(white),
    new bishop(white),
    new queen(white),
    new king(white),
    new bishop(white),
    new empty(),
    new rook(white),
  ],
]
